apiVersion: v1
kind: Pod
metadata:
  name: kao-note-back-end
spec:
  containers:
    - name: kao-note-back-end-container
      image: taykita/kaonote:kao-note-back-end
      ports:
        - containerPort: 8081
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "DEV"
    - name: kao-gateway
      image: taykita/kaonote:kao-note-gateway
      ports:
        - containerPort: 7857
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "DEV-BACK"